[package]
name = "deka"
version = "0.6.5"
description = "Дека — ретро-плеер с поддержкой VK Музыки"
edition = "2021"

[lib]
name = "deka_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
