[package]
name = "deka2"
version = "0.2.1"
description = "Дека 2 — отдельный DJ-плеер"
edition = "2021"

[lib]
name = "deka2_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
