const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const binary = path.join(root, 'src-tauri/target/release/deka2.exe');
const nsis = path.join(root, 'src-tauri/target/release/bundle/nsis');
if (!fs.existsSync(binary)) throw new Error('Deka 2 Windows binary was not produced');
const setups = fs.readdirSync(nsis).filter(x => x.toLowerCase().endsWith('.exe'));
if (setups.length !== 1) throw new Error('Expected exactly one Deka 2 installer');
fs.copyFileSync(binary, path.join(root, 'Deka2.exe'));
fs.copyFileSync(path.join(nsis, setups[0]), path.join(root, 'Deka2-setup.exe'));
console.log('Created Deka2.exe and Deka2-setup.exe. Original Deka is unchanged.');
